server:
  port: 8081

spring:
  datasource:
    username: admin
    password: password
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: DEBUG
